swagger: '2.0'
info:
  description: news のAPI仕様書
  version: 1.0.0
  title: News API
  contact:
    email: c8112002@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:8080'
basePath: /
tags:
  - name: articles
    description: 記事
schemes:
  - http
paths:
  /articles:
    get:
      tags:
        - articles
      summary: Fetch articles
      description: ''
      operationId: addPet
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: limit
          in: query
          description: 取得件数
          required: false
          type: number
          default: 5
        - name: offset
          in: query
          description: オフセット
          required: false
          type: number
          default: 0
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/Articles'
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
    flow: implicit
    scopes:
      'write:pets': modify pets in your account
      'read:pets': read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  Article:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
  Articles:
    type: array
    items:
      $ref: '#/definitions/Article'
